'use strict';
// DOM UI: topbar, resource sidebar, tab panels, toasts, modals, tooltips.
// Panels rebuild only when structure changes (UI.dirty()); dynamic values update
// via registered updater closures at ~5Hz for performance.

const UI = {
  activeTab: 'mine',
  updaters: [],
  _dirty: true,
  _toastKeys: {},
  _refreshT: 0,

  tabs: [
    { id: 'mine',      name: 'Mine',         icon: '⛏️' },
    { id: 'factories', name: 'Factories',    icon: '🏭' },
    { id: 'energy',    name: 'Energy',       icon: '⚡' },
    { id: 'research',  name: 'Research',     icon: '🔬' },
    { id: 'fleet',     name: 'Fleet',        icon: '🚀' },
    { id: 'ai',        name: 'AI',           icon: '🤖' },
    { id: 'planets',   name: 'Planets',      icon: '🪐' },
    { id: 'prestige',  name: 'Prestige',     icon: '🌌' },
    { id: 'achieve',   name: 'Awards',       icon: '🏆' },
    { id: 'stats',     name: 'Stats',        icon: '📊' },
    { id: 'settings',  name: 'Settings',     icon: '⚙️' },
  ],

  init() {
    this.buildTopbar();
    this.buildTabs();
    this.buildResourcePanel();
    this.showTab(this.activeTab);
    // Tooltip tracking
    const tip = document.getElementById('tooltip');
    document.addEventListener('mousemove', e => {
      const el = e.target.closest('[data-tip]');
      if (el) {
        tip.innerHTML = el.dataset.tip;
        tip.style.display = 'block';
        const tw = tip.offsetWidth, th = tip.offsetHeight;
        let x = e.clientX + 14, y = e.clientY + 14;
        if (x + tw > window.innerWidth - 8) x = e.clientX - tw - 10;
        if (y + th > window.innerHeight - 8) y = e.clientY - th - 10;
        tip.style.left = x + 'px';
        tip.style.top = y + 'px';
      } else {
        tip.style.display = 'none';
      }
    });
  },

  dirty() { this._dirty = true; },

  // ---------------------------------------------------------- topbar
  buildTopbar() {
    const el = document.getElementById('topbar');
    el.innerHTML = `
      <div class="brand"><span class="brand-icon">🛸</span><span class="brand-name">IDLE SPACE MINING</span></div>
      <div class="top-stats">
        <div class="top-stat" data-tip="Credits — the universal currency. Earned by selling resources and running factories.">
          <span class="ts-icon">💰</span><span class="ts-val" id="tb-credits">0</span>
          <span class="ts-sub" id="tb-cps"></span>
        </div>
        <div class="top-stat" data-tip="Research Points — generated by Research Labs. Spend in the Research tab.">
          <span class="ts-icon">🔬</span><span class="ts-val" id="tb-rp">0</span>
        </div>
        <div class="top-stat" data-tip="Energy: production / consumption. If consumption exceeds production, everything slows down.">
          <span class="ts-icon">⚡</span><span class="ts-val" id="tb-energy">0/0</span>
        </div>
        <div class="top-stat" data-tip="Galactic Energy from Ascension. Each point: +2% ALL production, forever.">
          <span class="ts-icon">🌌</span><span class="ts-val" id="tb-ge">0</span>
        </div>
      </div>
      <div class="buy-amount" data-tip="Purchase quantity for buildings">
        <button data-amt="1" class="amt-btn active">x1</button>
        <button data-amt="10" class="amt-btn">x10</button>
        <button data-amt="100" class="amt-btn">x100</button>
        <button data-amt="max" class="amt-btn">Max</button>
      </div>
      <button class="help-btn" id="btn-help" data-tip="How to play">❓</button>`;
    document.getElementById('btn-help').onclick = () => UI.helpModal();
    el.querySelectorAll('.amt-btn').forEach(b => {
      b.onclick = () => {
        Game.buyAmount = b.dataset.amt === 'max' ? 'max' : parseInt(b.dataset.amt);
        el.querySelectorAll('.amt-btn').forEach(x => x.classList.toggle('active', x === b));
        this.dirty();
      };
    });
  },

  updateTopbar() {
    document.getElementById('tb-credits').textContent = fmt(S.credits);
    document.getElementById('tb-cps').textContent = S.stats.cps > 0 ? '+' + fmt(S.stats.cps) + '/s' : '';
    document.getElementById('tb-rp').textContent = fmt(S.rp);
    const prod = Game.energyProd(), use = Game.energyUse();
    const en = document.getElementById('tb-energy');
    en.textContent = fmt(prod) + '/' + fmt(use);
    en.style.color = use > prod ? 'var(--bad)' : 'var(--text)';
    document.getElementById('tb-ge').textContent = fmt(S.ge);
  },

  // ---------------------------------------------------------- tabs
  buildTabs() {
    const nav = document.getElementById('tabs');
    nav.innerHTML = this.tabs.map(t =>
      `<button class="tab-btn" id="tab-${t.id}"><span>${t.icon}</span><span class="tab-name">${t.name}</span></button>`
    ).join('');
    this.tabs.forEach(t => {
      document.getElementById('tab-' + t.id).onclick = () => this.showTab(t.id);
    });
  },

  showTab(id) {
    this.activeTab = id;
    this.tabs.forEach(t =>
      document.getElementById('tab-' + t.id).classList.toggle('active', t.id === id));
    this.renderPanel();
  },

  // ---------------------------------------------------------- resources sidebar
  buildResourcePanel() {
    // structure only; rows are (re)built in updateResources when the set changes
    this._resSet = '';
  },

  updateResources() {
    const holder = document.getElementById('resources-panel');
    const visible = DATA.resources.filter(r => (S.resources[r.id] || 0) > 0.01);
    const key = visible.map(r => r.id).join(',') + (S.research.autosell ? '|a' : '');
    if (key !== this._resSet) {
      this._resSet = key;
      let html = `<div class="panel-title">📦 Cargo Hold ${S.research.autosell ? '<span class="badge-auto">AUTO-SELL</span>' : ''}</div>`;
      if (!visible.length) html += `<div class="res-empty">Click the planet to start mining!</div>`;
      for (const r of visible) {
        html += `<div class="res-row" data-tip="${r.name} — worth ${fmt(r.value)} credits each (${r.tier})">
          <span class="res-dot" style="background:${r.color}"></span>
          <span class="res-name">${r.name}</span>
          <span class="res-amt" id="res-${r.id}">0</span>
        </div>`;
      }
      html += `<button class="btn btn-sell" id="btn-sell">Sell All <span id="sell-val"></span></button>`;
      holder.innerHTML = html;
      const btn = document.getElementById('btn-sell');
      if (btn) btn.onclick = () => {
        const v = Game.sellAll();
        if (v > 0) {
          Sound.play('sell');
          const rect = document.getElementById('scene').getBoundingClientRect();
          Render.floatText('+' + fmt(v) + ' cr', rect.width / 2, rect.height * 0.25, '#ffd54a');
        }
      };
    }
    for (const r of visible) {
      const el = document.getElementById('res-' + r.id);
      if (el) el.textContent = fmt(S.resources[r.id] || 0);
    }
    const sv = document.getElementById('sell-val');
    if (sv) sv.textContent = '(+' + fmt(Game.sellValue()) + ')';
  },

  updatePlanetInfo() {
    const el = document.getElementById('planet-info');
    const p = DATA.planetMap[S.currentPlanet];
    if (this._piKey !== p.id) {
      this._piKey = p.id;
      const chips = Object.entries(p.dist).map(([rid, w]) => {
        const r = DATA.resourceMap[rid];
        return `<span class="chip" style="border-color:${r.color}55" data-tip="${r.name}: ${Math.round(w * 100)}% of mined ore">
          <span class="res-dot" style="background:${r.color}"></span>${Math.round(w * 100)}%</span>`;
      }).join('');
      el.innerHTML = `<div class="pi-name">${p.name} <span class="pi-mult">×${fmt(p.mult)} mining</span></div>
        <div class="pi-chips">${chips}</div>
        <div class="pi-rates"><span data-tip="Ore mined automatically per second" id="pi-ore"></span>
        <span data-tip="Ore per click" id="pi-click"></span></div>`;
    }
    document.getElementById('pi-ore').textContent = '⛏️ ' + fmt(Game.oreRate()) + ' ore/s';
    document.getElementById('pi-click').textContent = '👆 ' + fmt(Game.clickPower()) + '/click';
  },

  updateEventBanner() {
    const el = document.getElementById('event-banner');
    if (S.event) {
      const def = DATA.eventMap[S.event.id];
      const left = Math.max(0, (S.event.endsAt - Date.now()) / 1000);
      el.style.display = 'flex';
      el.className = 'event-banner ' + (def.good ? 'ev-good' : 'ev-bad');
      el.innerHTML = `<span>${def.icon} <b>${def.name}</b> — ${def.desc}</span><span class="ev-timer">${Math.ceil(left)}s</span>`;
    } else {
      el.style.display = 'none';
    }
  },

  // ---------------------------------------------------------- generic buy row
  buyRow(parent, opts) {
    const row = document.createElement('div');
    row.className = 'buy-row';
    if (opts.tip) row.dataset.tip = opts.tip;
    row.innerHTML = `
      <div class="br-icon">${opts.icon}</div>
      <div class="br-body">
        <div class="br-name">${opts.name} <span class="br-count"></span></div>
        <div class="br-desc">${opts.desc || ''}</div>
      </div>
      <button class="btn btn-buy"><span class="bb-label"></span><span class="bb-cost"></span></button>`;
    const countEl = row.querySelector('.br-count');
    const btn = row.querySelector('.btn-buy');
    const labelEl = row.querySelector('.bb-label');
    const costEl = row.querySelector('.bb-cost');
    btn.onclick = opts.onBuy;
    parent.appendChild(row);
    this.updaters.push(() => {
      countEl.textContent = opts.countFn ? opts.countFn() : '';
      labelEl.textContent = opts.labelFn ? opts.labelFn() : 'Buy';
      costEl.textContent = opts.costFn();
      btn.disabled = !opts.canFn();
      if (opts.descFn) row.querySelector('.br-desc').innerHTML = opts.descFn();
    });
    return row;
  },

  // ---------------------------------------------------------- panels
  renderPanel() {
    this.updaters = [];
    const panel = document.getElementById('panel');
    panel.innerHTML = '';
    const fn = this['panel_' + this.activeTab];
    if (fn) fn.call(this, panel);
    this._dirty = false;
    this.runUpdaters();
  },

  runUpdaters() {
    for (const u of this.updaters) { try { u(); } catch (e) { /* row removed */ } }
  },

  section(panel, title, sub) {
    const d = document.createElement('div');
    d.className = 'panel-section';
    d.innerHTML = `<div class="panel-title">${title}</div>` + (sub ? `<div class="panel-sub">${sub}</div>` : '');
    panel.appendChild(d);
    return d;
  },

  panel_mine(panel) {
    const s1 = this.section(panel, '👆 Manual Mining');
    this.buyRow(s1, {
      icon: '🔧', name: 'Drill Power',
      desc: 'Upgrade your manual drill. +1 base ore per click.',
      tip: 'Click power = (1 + drill level) × all mining multipliers',
      countFn: () => 'Lv ' + S.drill,
      labelFn: () => 'Upgrade',
      costFn: () => fmt(Game.drillCost()) + ' cr',
      canFn: () => S.credits >= Game.drillCost(),
      onBuy: () => Game.buyDrill(),
    });

    const s2 = this.section(panel, '🛸 Automated Miners', 'Miners produce ore every second on your current planet.');
    DATA.miners.forEach((m, i) => {
      // A tier appears once you own at least one of the previous tier
      if (i > 0 && !(S.miners[DATA.miners[i - 1].id] > 0) && !(S.miners[m.id] > 0)) return;
      this.buyRow(s2, {
        icon: m.icon, name: m.name, desc: m.desc,
        tip: `${m.name}<br>Base production: ${fmt(m.prod)} ore/s each<br>Energy use: ${m.energy}/each`,
        countFn: () => {
          const c = S.miners[m.id] || 0;
          return c > 0 ? '×' + fmtInt(c) + ' · ' + fmt(c * m.prod * Game.miningMult() * Game.energyEff()) + '/s' : '';
        },
        labelFn: () => Game.buyAmount === 'max' ? 'Max' : 'x' + Game.buyAmount,
        costFn: () => fmt(Game.buyPlan(m.cost, DATA.minerCostMult, S.miners[m.id] || 0).cost) + ' cr',
        canFn: () => {
          const plan = Game.buyPlan(m.cost, DATA.minerCostMult, S.miners[m.id] || 0);
          return S.credits >= plan.cost && plan.n >= 1;
        },
        onBuy: () => Game.buyMiner(m.id),
      });
    });
  },

  panel_factories(panel) {
    const s = this.section(panel, '🏭 Refinement Factories',
      'Factories consume raw ore and produce refined goods sold automatically at a premium. They need energy and a steady ore supply.');
    DATA.factories.forEach(f => {
      const res = DATA.resourceMap[f.input];
      this.buyRow(s, {
        icon: f.icon, name: f.name,
        desc: `${f.inRate} ${res.name}/s → <b style="color:var(--gold)">${fmt(f.outCr)} cr/s</b> (${f.product})`,
        tip: `${f.name}<br>Consumes ${f.inRate} ${res.name}/s each<br>Produces ${fmt(f.outCr)} credits/s each (before multipliers)<br>Energy: ${f.energy}/each`,
        countFn: () => {
          const c = S.factories[f.id] || 0;
          return c > 0 ? '×' + fmtInt(c) : '';
        },
        labelFn: () => Game.buyAmount === 'max' ? 'Max' : 'x' + Game.buyAmount,
        costFn: () => fmt(Game.buyPlan(f.cost, DATA.factoryCostMult, S.factories[f.id] || 0).cost) + ' cr',
        canFn: () => {
          const plan = Game.buyPlan(f.cost, DATA.factoryCostMult, S.factories[f.id] || 0);
          return S.credits >= plan.cost && plan.n >= 1;
        },
        onBuy: () => Game.buyFactory(f.id),
      });
    });
    const note = document.createElement('div');
    note.className = 'panel-sub';
    this.updaters.push(() => {
      note.innerHTML = `Factory multiplier: ×${fmt(Game.factoryMult())} · Energy efficiency: ${Math.round(Game.energyEff() * 100)}%`;
    });
    panel.appendChild(note);
  },

  panel_energy(panel) {
    const s0 = this.section(panel, '⚡ Power Grid');
    const bar = document.createElement('div');
    bar.className = 'energy-box';
    bar.innerHTML = `<div class="energy-nums" id="en-nums"></div><div class="energy-bar"><div class="energy-fill" id="en-fill"></div></div>`;
    s0.appendChild(bar);
    this.updaters.push(() => {
      const prod = Game.energyProd(), use = Game.energyUse();
      const eff = Game.energyEff();
      document.getElementById('en-nums').innerHTML =
        `Production: <b>${fmt(prod)}</b> · Consumption: <b>${fmt(use)}</b> · Efficiency: <b style="color:${eff < 1 ? 'var(--bad)' : 'var(--good)'}">${Math.round(eff * 100)}%</b>`;
      const fill = document.getElementById('en-fill');
      const pct = prod <= 0 ? 0 : Math.min(100, (use / prod) * 100);
      fill.style.width = pct + '%';
      fill.style.background = use > prod ? 'var(--bad)' : pct > 80 ? 'var(--gold)' : 'var(--good)';
    });

    const s = this.section(panel, '🔋 Generators', 'When consumption exceeds production, miners, factories and labs all slow down proportionally.');
    DATA.generators.forEach(g => {
      this.buyRow(s, {
        icon: g.icon, name: g.name, desc: g.desc + ` <b style="color:var(--accent)">+${fmt(g.out)} energy</b>`,
        countFn: () => { const c = S.generators[g.id] || 0; return c > 0 ? '×' + fmtInt(c) : ''; },
        labelFn: () => Game.buyAmount === 'max' ? 'Max' : 'x' + Game.buyAmount,
        costFn: () => fmt(Game.buyPlan(g.cost, DATA.generatorCostMult, S.generators[g.id] || 0).cost) + ' cr',
        canFn: () => {
          const plan = Game.buyPlan(g.cost, DATA.generatorCostMult, S.generators[g.id] || 0);
          return S.credits >= plan.cost && plan.n >= 1;
        },
        onBuy: () => Game.buyGenerator(g.id),
      });
    });
  },

  panel_research(panel) {
    const s0 = this.section(panel, '🧪 Research Labs', 'Labs generate Research Points (RP) over time.');
    this.buyRow(s0, {
      icon: '🧪', name: 'Research Lab',
      desc: `Generates ${DATA.labs.rate} RP/s each. Energy: ${DATA.labs.energy}/each.`,
      countFn: () => S.labs > 0 ? '×' + fmtInt(S.labs) + ' · ' + fmt(Game.rpRate()) + ' RP/s' : '',
      labelFn: () => Game.buyAmount === 'max' ? 'Max' : 'x' + Game.buyAmount,
      costFn: () => fmt(Game.buyPlan(DATA.labs.cost, DATA.labs.costMult, S.labs).cost) + ' cr',
      canFn: () => {
        const plan = Game.buyPlan(DATA.labs.cost, DATA.labs.costMult, S.labs);
        return S.credits >= plan.cost && plan.n >= 1;
      },
      onBuy: () => Game.buyLab(),
    });

    const cats = [...new Set(DATA.research.map(r => r.cat))];
    for (const cat of cats) {
      const s = this.section(panel, '🔬 ' + cat);
      for (const r of DATA.research.filter(x => x.cat === cat)) {
        const row = document.createElement('div');
        row.className = 'buy-row research-row';
        row.dataset.tip = r.desc + (r.req ? '<br>Requires: ' + DATA.researchMap[r.req].name : '');
        row.innerHTML = `
          <div class="br-icon">${S.research[r.id] ? '✅' : '🔬'}</div>
          <div class="br-body"><div class="br-name">${r.name}</div><div class="br-desc">${r.desc}</div></div>
          <button class="btn btn-buy"><span class="bb-cost">${fmt(r.cost)} RP</span></button>`;
        const btn = row.querySelector('.btn-buy');
        btn.onclick = () => Game.buyResearch(r.id);
        s.appendChild(row);
        this.updaters.push(() => {
          const owned = !!S.research[r.id];
          const locked = r.req && !S.research[r.req];
          row.classList.toggle('owned', owned);
          row.classList.toggle('locked', locked && !owned);
          row.querySelector('.br-icon').textContent = owned ? '✅' : locked ? '🔒' : '🔬';
          btn.style.display = owned ? 'none' : '';
          btn.disabled = locked || S.rp < r.cost;
        });
      }
    }
  },

  panel_fleet(panel) {
    const s = this.section(panel, '🚀 Fleet Shipyard', 'Each ship grants a permanent bonus per level.');
    DATA.ships.forEach(sh => {
      this.buyRow(s, {
        icon: sh.icon, name: sh.name, desc: sh.desc,
        countFn: () => {
          const lvl = S.ships[sh.id] || 0;
          return lvl > 0 ? 'Lv ' + lvl + '/' + sh.max : '';
        },
        labelFn: () => (S.ships[sh.id] || 0) >= sh.max ? 'MAX' : 'Buy',
        costFn: () => (S.ships[sh.id] || 0) >= sh.max ? '' : fmt(Game.shipCost(sh.id)) + ' cr',
        canFn: () => (S.ships[sh.id] || 0) < sh.max && S.credits >= Game.shipCost(sh.id),
        onBuy: () => Game.buyShip(sh.id),
      });
    });

    const s2 = this.section(panel, '🔭 Exploration',
      'Send your Explorer into the unknown. Rewards scale with your economy. Requires an Explorer ship.');
    const missionBox = document.createElement('div');
    s2.appendChild(missionBox);

    const buildMissions = () => {
      missionBox.innerHTML = '';
      if (S.mission) {
        const m = DATA.missionMap[S.mission.id];
        const box = document.createElement('div');
        box.className = 'mission-active';
        box.innerHTML = `<div>${m.icon} <b>${m.name}</b> in progress…</div>
          <div class="energy-bar"><div class="energy-fill" id="mi-fill" style="background:var(--accent)"></div></div>
          <div id="mi-left" class="panel-sub"></div>`;
        missionBox.appendChild(box);
      } else {
        DATA.missions.forEach(m => {
          const dur = Game.missionDuration(m);
          this.buyRow(missionBox, {
            icon: m.icon, name: m.name, desc: m.desc + ` · ${fmtTime(dur)} · reward ×${m.mult}`,
            tip: 'Reward ≈ credits/sec × duration × ' + m.mult,
            countFn: () => '',
            labelFn: () => 'Launch',
            costFn: () => '',
            canFn: () => !S.mission && (S.ships.explorer || 0) > 0,
            onBuy: () => Game.startMission(m.id),
          });
        });
        if (!(S.ships.explorer > 0)) {
          const warn = document.createElement('div');
          warn.className = 'panel-sub';
          warn.innerHTML = '⚠️ Buy an <b>Explorer</b> ship above to launch missions.';
          missionBox.appendChild(warn);
        }
      }
    };
    buildMissions();
    this._missionState = !!S.mission;
    this.updaters.push(() => {
      const now = !!S.mission;
      if (now !== this._missionState) { this._missionState = now; this.renderPanel(); return; }
      if (S.mission) {
        const total = S.mission.endsAt - S.mission.startedAt;
        const done = Date.now() - S.mission.startedAt;
        const fill = document.getElementById('mi-fill');
        const left = document.getElementById('mi-left');
        if (fill) fill.style.width = Math.min(100, done / total * 100) + '%';
        if (left) left.textContent = fmtTime((S.mission.endsAt - Date.now()) / 1000) + ' remaining';
      }
    });
  },

  panel_ai(panel) {
    const s = this.section(panel, '🤖 AI Managers', 'Hire once. Powerful permanent bonuses. They never ask for a raise.');
    DATA.managers.forEach(m => {
      const row = document.createElement('div');
      row.className = 'buy-row ai-row';
      row.innerHTML = `
        <div class="br-icon">${m.icon}</div>
        <div class="br-body"><div class="br-name">${m.name}</div><div class="br-desc">${m.desc}</div></div>
        <button class="btn btn-buy"><span class="bb-cost">${fmt(m.cost)} cr</span></button>`;
      const btn = row.querySelector('.btn-buy');
      btn.onclick = () => Game.buyManager(m.id);
      s.appendChild(row);
      this.updaters.push(() => {
        const owned = !!S.managers[m.id];
        row.classList.toggle('owned', owned);
        btn.style.display = owned ? 'none' : '';
        btn.disabled = S.credits < m.cost;
        row.querySelector('.br-icon').textContent = owned ? '✅' : m.icon;
        if (owned) row.querySelector('.br-name').innerHTML = m.name + ' <span class="badge-online">ONLINE</span>';
      });
    });
  },

  panel_planets(panel) {
    const s = this.section(panel, '🪐 Galactic Map', 'Unlock new worlds with richer ores and higher mining multipliers. Your whole fleet relocates when you switch planets.');
    DATA.planets.forEach((p, i) => {
      const card = document.createElement('div');
      card.className = 'planet-card';
      const distHtml = Object.entries(p.dist).map(([rid, w]) => {
        const r = DATA.resourceMap[rid];
        return `<span class="chip sm" style="border-color:${r.color}55" data-tip="${r.name} · ${Math.round(w * 100)}% · worth ${fmt(r.value)} cr each">
          <span class="res-dot" style="background:${r.color}"></span>${r.name}</span>`;
      }).join('');
      card.innerHTML = `
        <div class="pc-orb" style="background:radial-gradient(circle at 35% 35%, ${p.colors[0]}, ${p.colors[1]});box-shadow:0 0 18px ${p.colors[2]}66"></div>
        <div class="pc-body">
          <div class="pc-name">${p.name} <span class="pi-mult">×${fmt(p.mult)}</span></div>
          <div class="pc-desc">${p.desc}</div>
          <div class="pc-dist">${distHtml}</div>
        </div>
        <div class="pc-action"></div>`;
      const action = card.querySelector('.pc-action');
      s.appendChild(card);
      this.updaters.push(() => {
        const unlocked = !!S.planets[p.id];
        const current = S.currentPlanet === p.id;
        card.classList.toggle('current', current);
        card.classList.toggle('locked-card', !unlocked);
        if (current) {
          action.innerHTML = '<span class="badge-online">ACTIVE</span>';
        } else if (unlocked) {
          if (!action.querySelector('.btn')) {
            action.innerHTML = '<button class="btn btn-buy">Travel</button>';
            action.querySelector('.btn').onclick = () => Game.selectPlanet(p.id);
          }
        } else {
          if (!action.querySelector('.btn')) {
            action.innerHTML = `<button class="btn btn-buy"><span class="bb-cost">${fmt(p.cost)} cr</span></button>`;
            action.querySelector('.btn').onclick = () => Game.unlockPlanet(p.id);
          }
          action.querySelector('.btn').disabled = S.credits < p.cost;
        }
      });
    });
  },

  panel_prestige(panel) {
    const s = this.section(panel, '🌌 Galactic Ascension',
      'Collapse your empire into pure Galactic Energy and begin anew — stronger. Each Galactic Energy grants <b>+2% ALL production, permanently</b>. You keep achievements. Everything else resets.');
    const box = document.createElement('div');
    box.className = 'prestige-box';
    box.innerHTML = `
      <div class="pr-stat">Current Galactic Energy: <b id="pr-ge"></b> <span class="panel-sub" id="pr-bonus"></span></div>
      <div class="pr-stat">Credits earned this run: <b id="pr-run"></b></div>
      <div class="pr-stat">Ascension yield: <b id="pr-pending" style="color:var(--purple)"></b></div>
      <div class="panel-sub" id="pr-hint"></div>
      <button class="btn btn-prestige" id="btn-prestige">🌌 ASCEND</button>`;
    s.appendChild(box);
    document.getElementById('btn-prestige').onclick = () => {
      const gain = Game.pendingGE();
      if (gain < 1) return;
      UI.modal(`
        <h2>🌌 Galactic Ascension</h2>
        <p>You will gain <b style="color:var(--purple)">${gain} Galactic Energy</b> (+${gain * 2}% all production, forever).</p>
        <p>Your credits, resources, miners, factories, research, ships, AI and planets will reset.<br>Achievements and Galactic Energy are permanent.</p>
        <div class="modal-actions">
          <button class="btn btn-prestige" onclick="Game.prestige()">Ascend Now</button>
          <button class="btn" onclick="UI.closeModal()">Not Yet</button>
        </div>`);
    };
    this.updaters.push(() => {
      const pending = Game.pendingGE();
      document.getElementById('pr-ge').textContent = fmt(S.ge);
      document.getElementById('pr-bonus').textContent = '(+' + fmt(S.ge * 2) + '% all production)';
      document.getElementById('pr-run').textContent = fmt(S.runCredits);
      document.getElementById('pr-pending').textContent = '+' + fmt(pending) + ' GE';
      const hint = document.getElementById('pr-hint');
      hint.innerHTML = pending < 1
        ? 'Earn at least <b>1T credits</b> in a single run to Ascend. Progress: ' + fmt(S.runCredits) + ' / 1T'
        : 'After ascending: +' + fmt((S.ge + pending) * 2) + '% total production bonus.';
      document.getElementById('btn-prestige').disabled = pending < 1;
    });
  },

  panel_achieve(panel) {
    const s = this.section(panel, '🏆 Achievements', 'Each unlocked achievement grants +1% ALL production.');
    const grid = document.createElement('div');
    grid.className = 'ach-grid';
    s.appendChild(grid);
    DATA.achievements.forEach(a => {
      const cell = document.createElement('div');
      cell.className = 'ach-cell';
      cell.dataset.tip = `<b>${a.name}</b><br>${a.desc}`;
      cell.innerHTML = `<div class="ach-icon">🏆</div><div class="ach-name">${a.name}</div>`;
      grid.appendChild(cell);
      this.updaters.push(() => {
        cell.classList.toggle('unlocked', !!S.achievements[a.id]);
      });
    });
    const count = document.createElement('div');
    count.className = 'panel-sub';
    panel.appendChild(count);
    this.updaters.push(() => {
      count.textContent = Object.keys(S.achievements).length + ' / ' + DATA.achievements.length +
        ' unlocked · +' + Object.keys(S.achievements).length + '% all production';
    });
  },

  panel_stats(panel) {
    const s = this.section(panel, '📊 Statistics');
    const list = document.createElement('div');
    list.className = 'stats-list';
    s.appendChild(list);
    this.updaters.push(() => {
      const rows = [
        ['Total ore mined', fmt(S.stats.oreMined)],
        ['Lifetime credits earned', fmt(S.stats.creditsEarned)],
        ['Credits (this run)', fmt(S.runCredits)],
        ['Manual clicks', fmt(S.stats.clicks)],
        ['Current income', fmt(S.stats.cps) + ' cr/s'],
        ['Best income', fmt(S.stats.bestCps) + ' cr/s'],
        ['Total miners owned', fmtInt(Game.totalMiners())],
        ['Total factories', fmtInt(Game.totalFactories())],
        ['Research labs', fmtInt(S.labs)],
        ['Research completed', Object.keys(S.research).length + ' / ' + DATA.research.length],
        ['Research points earned', fmt(S.stats.rpEarned)],
        ['Planets unlocked', Object.keys(S.planets).length + ' / ' + DATA.planets.length],
        ['Exploration missions', fmtInt(S.stats.missions)],
        ['Random events witnessed', fmtInt(S.stats.eventsSeen)],
        ['Galactic Ascensions', fmtInt(S.prestiges)],
        ['Galactic Energy', fmt(S.ge)],
        ['Achievements', Object.keys(S.achievements).length + ' / ' + DATA.achievements.length],
        ['Automation share', (Game.oreRate() > 0 ? Math.round(100 * Game.oreRate() / (Game.oreRate() + Game.clickPower())) : 0) + '% of potential ore/s'],
        ['Play time', fmtTime(S.stats.playTime)],
      ];
      list.innerHTML = rows.map(([k, v]) => `<div class="stat-row"><span>${k}</span><b>${v}</b></div>`).join('');
    });
  },

  panel_settings(panel) {
    const s = this.section(panel, '⚙️ Settings');
    s.insertAdjacentHTML('beforeend', `
      <div class="setting-row"><label>Sound effects</label>
        <input type="range" min="0" max="1" step="0.05" id="set-sfx" value="${S.settings.sfx}"></div>
      <div class="setting-row"><label>Music</label>
        <input type="range" min="0" max="1" step="0.05" id="set-music" value="${S.settings.music}"></div>
      <div class="setting-row"><label>Particles</label>
        <input type="checkbox" id="set-parts" ${S.settings.particles ? 'checked' : ''}></div>
      <div class="setting-row"><label>Performance mode <span class="panel-sub">(fewer visual effects)</span></label>
        <input type="checkbox" id="set-perf" ${S.settings.perf ? 'checked' : ''}></div>
      <div class="settings-btns">
        <button class="btn" id="set-help">❓ How to Play</button>
        <button class="btn" id="set-tut">🎓 Replay Tutorial</button>
        <button class="btn" id="set-save">💾 Save Now</button>
        <button class="btn" id="set-export">📤 Export Save</button>
        <button class="btn" id="set-import">📥 Import Save</button>
        <button class="btn btn-danger" id="set-reset">☠️ Hard Reset</button>
      </div>
      <div class="panel-sub">Game autosaves every 15 seconds and when you close the tab. Offline progress is collected on return (cap 12h, or 24h with Deep Space Comms research).</div>
      <div class="panel-sub">Shortcuts: <b>1–9, 0, -</b> switch tabs · <b>Space</b> mines once.</div>`);
    document.getElementById('set-sfx').oninput = e => { S.settings.sfx = parseFloat(e.target.value); };
    document.getElementById('set-music').oninput = e => { S.settings.music = parseFloat(e.target.value); Sound.updateVolumes(); };
    document.getElementById('set-parts').onchange = e => { S.settings.particles = e.target.checked; };
    document.getElementById('set-perf').onchange = e => { S.settings.perf = e.target.checked; };
    document.getElementById('set-help').onclick = () => UI.helpModal();
    document.getElementById('set-tut').onclick = () => TUTORIAL.replay();
    document.getElementById('set-save').onclick = () => { saveState(); UI.toast('💾 Game saved', 'info'); };
    document.getElementById('set-export').onclick = () => {
      const code = exportSave();
      UI.modal(`<h2>📤 Export Save</h2><p>Copy this code somewhere safe:</p>
        <textarea class="save-area" readonly onclick="this.select()">${code}</textarea>
        <div class="modal-actions"><button class="btn" onclick="UI.closeModal()">Close</button></div>`);
    };
    document.getElementById('set-import').onclick = () => {
      UI.modal(`<h2>📥 Import Save</h2><p>Paste your save code:</p>
        <textarea class="save-area" id="import-area" placeholder="Paste save code here…"></textarea>
        <div class="modal-actions">
          <button class="btn" onclick="UI.doImport()">Import</button>
          <button class="btn" onclick="UI.closeModal()">Cancel</button>
        </div>`);
    };
    document.getElementById('set-reset').onclick = () => {
      UI.modal(`<h2>☠️ Hard Reset</h2><p>This erases <b>everything</b> — including Galactic Energy and achievements. There is no undo.</p>
        <div class="modal-actions">
          <button class="btn btn-danger" onclick="hardReset()">Erase Everything</button>
          <button class="btn" onclick="UI.closeModal()">Cancel</button>
        </div>`);
    };
  },

  doImport() {
    const val = document.getElementById('import-area').value;
    if (importSave(val)) location.reload();
    else UI.toast('❌ Invalid save code', 'bad');
  },

  // ---------------------------------------------------------- toasts & modals
  toast(msg, cls, dur) {
    const holder = document.getElementById('toasts');
    const el = document.createElement('div');
    el.className = 'toast ' + (cls || 'info');
    el.innerHTML = msg;
    holder.appendChild(el);
    while (holder.children.length > 5) holder.removeChild(holder.firstChild);
    setTimeout(() => el.classList.add('show'), 10);
    setTimeout(() => {
      el.classList.remove('show');
      setTimeout(() => el.remove(), 400);
    }, dur || 4000);
  },

  toastOnceKey(key, msg) {
    if (this._toastKeys[key]) return;
    this._toastKeys[key] = 1;
    this.toast(msg, 'info');
  },

  modal(html) {
    const root = document.getElementById('modal-root');
    root.innerHTML = `<div class="modal-back"><div class="modal">${html}</div></div>`;
    root.querySelector('.modal-back').onclick = e => { if (e.target.classList.contains('modal-back')) this.closeModal(); };
  },

  closeModal() {
    document.getElementById('modal-root').innerHTML = '';
  },

  offlineModal(o) {
    this.modal(`
      <h2>🛰️ Welcome back, Commander</h2>
      <p>You were away for <b>${fmtTime(o.away)}</b>. Your automated empire kept working${o.counted < o.away ? ' (capped at ' + fmtTime(o.counted) + ')' : ''} at ${Math.round(o.rate * 100)}% efficiency:</p>
      <div class="offline-gains">
        ${o.ore > 0 ? '<div>⛏️ Ore mined: <b>' + fmt(o.ore) + '</b></div>' : ''}
        ${o.credits > 0 ? '<div>💰 Credits earned: <b>' + fmt(o.credits) + '</b></div>' : ''}
        ${o.rp > 0 ? '<div>🔬 Research points: <b>' + fmt(o.rp) + '</b></div>' : ''}
        ${o.ore <= 0 && o.credits <= 0 && o.rp <= 0 ? '<div>Your operation was idle — buy some miners!</div>' : ''}
      </div>
      <div class="modal-actions"><button class="btn btn-buy" onclick="UI.closeModal()">Collect</button></div>`);
  },

  // ---------------------------------------------------------- refresh loop
  refresh(dt) {
    this._refreshT += dt;
    if (this._dirty) { this.renderPanel(); }
    if (this._refreshT >= 0.2) {
      this._refreshT = 0;
      this.updateTopbar();
      this.updateResources();
      this.updatePlanetInfo();
      this.updateEventBanner();
      this.runUpdaters();
      if (typeof TUTORIAL !== 'undefined') TUTORIAL.refresh();
    }
  },
};
